CREATE DATABASE FFighter;

create table JOGADOR (
	ID_JOGADOR int PRIMARY KEY IDENTITY,
	LOGIN_JOGADOR VARCHAR(50) NOT NULL,
	SENHA_JOGADOR VARCHAR(50) NOT NULL
)
Go

create table ITENS(
	ID_ITEM int PRIMARY KEY IDENTITY ,
	NOME VARCHAR(30) NOT NULL,
	CATEGORIA VARCHAR(20),
	QUANTIDADE INT NOT NULL
)
GO

create table PERSONAGEM (
	ID_PERSONAGEM int PRIMARY KEY IDENTITY,
	NOME VARCHAR(20) NOT NULL,
	SEXO CHAR(1) CHECK(SEXO IN ('M','F')) NOT NULL,
	FK_ID_JOGADOR INT FOREIGN KEY REFERENCES JOGADOR (ID_JOGADOR) NOT NULL,
	ID_REFERENCIA VARCHAR(30),
)
GO

create table FASE(
	ID_FASE INT PRIMARY KEY IDENTITY,
	NUMERO_FAZE INT,
	NIVEL_DIFICULDADE VARCHAR(20)
)
GO

create table BOT(
	ID_BOT INT NOT NULL PRIMARY KEY,
	FK_ID_ITEM INT FOREIGN KEY REFERENCES ITENS (ID_ITEM) NOT NULL,
	FK_ID_FASE INT FOREIGN KEY REFERENCES FASE (ID_FASE) NOT NULL
)
GO

create table NIVEL_PERSONAGEM(
	ID_NIVEL INT PRIMARY KEY NOT NULL,
	NUMERO_NIVEL INT NOT NULL,
	QUANRIDADE_XP INT NOT NULL,
	FK_ID_PERSONAGEM INT FOREIGN KEY REFERENCES PERSONAGEM (ID_PERSONAGEM) NOT NULL
)
GO

create table ITEM_PERSONAGEM(
	ID_ITEM_PERSONAGEM INT PRIMARY KEY IDENTITY,
	FK_ID_PERSONAGEM INT FOREIGN KEY REFERENCES PERSONAGEM (ID_PERSONAGEM) NOT NULL,
	FK_ID_ITEM INT FOREIGN KEY REFERENCES ITENS (ID_ITEM) NOT NULL
)
GO